apiVersion: redis.kun/v1alpha1
kind: RedisClusterBackup
metadata:
  name: redis-test
  namespace: redis
  annotations:
    redis.kun/scope: cluster-scoped
spec:
  image: registry.pulsepoint.com/redis-tools:1.0.5-operator
  redisClusterName: example-2
  local:
    mountPath: /back
    persistentVolumeClaim:
      claimName: redis-test
