apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: redis-operator-validation-webhook
webhooks:
  - name: drc.redis.kun
    failurePolicy: Fail
    clientConfig:
      service:
        name: redis-cluster-webhook
        namespace: redis
        path: /validate-redis-kun-v1alpha1-distributedrediscluster
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKVENDQWcyZ0F3SUJBZ0lVVVdBT3hoSnZUYnZXd3RBSGJtdElDTmhNU05Nd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lqRWdNQjRHQTFVRUF3d1hRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnUTBFd0hoY05NalV3TkRBMgpNVE0xTXpNMVdoY05NelV3TkRBME1UTTFNek0xV2pBaU1TQXdIZ1lEVlFRRERCZEJaRzFwYzNOcGIyNGdRMjl1CmRISnZiR3hsY2lCRFFUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUt1Y1RKUFkKT3BjSjdDeUlxQnhjOE1KYURXMnVObjZaRDRqMWd0UFpMcHVMWm5PZngvVXRPbXFnbUZiVXRXcjE2ZzkvY3gvcApyU0xMN05zbVZyK3d0WVNGQ0dwTW9MZjM1RnlDV1pMSEl3Ymowb2FENTRhTFBoVS9Xc2o4ZThwQ2VmU1Voc2V1CjZ0L2N0eDl2OHk3bC9FL3hrYTB3dGpvRU1WLzFGM2FGczB4YVFuT3dLRURpd2MxRFN4N2I2SGJpMTlUc1BQNTYKbk5aSlNOTXJDeUQ4djViOW5rRENwMXhQcU4xcVlVeTVzb3hJaFUzaEd0NkFwRS91RTdKZGN2SlI3cVV3WDFJUwpRTDU3czVQaHluM3laanUwMUkreC93VmlBcnRlVWZ0TXc2TFlqQzlsYzZWUkZvcHZRU3l5YjJMOXhrZmZUa0lPCmtWMll3QXoxSHVzai9jVUNBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGTnhXZzVSL2dTVnEyUzR6cXRIU08rK0EKNHdvSU1COEdBMVVkSXdRWU1CYUFGTnhXZzVSL2dTVnEyUzR6cXRIU08rK0E0d29JTUE4R0ExVWRFd0VCL3dRRgpNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHQllqbngrV2xuUWN0OHQ4YWFGUnRqR2R1M05qYzFHCnI0Y01qcDdBTWRJa0xMY0lCRzJKV3RROFJRNTMyS0dmenNqS2dVTlpIS3V6UlpmWEErZXVtTUk4ZE05VTZQZnoKUmlLcFF4bDZzQmtJbmcyZmlYVWFEblNudEhJc1VreFVrQW1zMmpGYS9yK2RpRnlWYUZZWFU1LzRPZW9DNzYzTQo4czM0alFXYkl0clVYMklDRUZyMXF1M2dLU0dMdVgwTktuTHVYZmErOEZjc2xjaFowa2dYVkRkZEMxVmNSS21sCmpsa0tKcFdtZTJxOWNkQlR1T0ZEeVA1NXZCMUtuNUY5ei9KL0l5eHZpSVNWekwzcFNOQzhMM1dBNjVUSGtpdTQKNG9CQ0dVbnJ5aWFYdVQzYmxnbk4zeXJwSjh0Z0t2NnJZVTNRbkEzWmhPaU10WXVCVDJ3OGNjUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations:
          - DELETE
        apiGroups:
          - redis.kun
        apiVersions:
          - v1alpha1
        resources:
          - distributedredisclusters