apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cluster-operator
  namespace: redis
spec:
  selector:
    matchLabels:
      name: redis-cluster-operator
  template:
    metadata:
      labels:
        name: redis-cluster-operator
    spec:
      serviceAccountName: redis-cluster-operator
      securityContext:
        fsGroup: 1100
        runAsGroup: 1100
        runAsUser: 1100
        supplementalGroups:
          - 1100
      containers:
        - name: redis-cluster-operator
          image: registry.pulsepoint.com/redis-cluster-operator:v0.3.29-pp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          command:
            - redis-cluster-operator
          args:
            - --rename-command-path=/etc/redisconf
            - --rename-command-file=redis.conf
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: ENABLE_WEBHOOKS
              value: "true"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "redis-cluster-operator"
          volumeMounts:
            - name: redisconf
              mountPath: /etc/redisconf
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: redisconf
          configMap:
            name: redis-admin
        - name: webhook-certs
          secret:
            secretName: drc-webhook-cert