apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-webhook
  namespace: redis
  labels:
    app: redis-cluster-webhook
spec:
  ports:
    - port: 443
      targetPort: 7443
  selector:
    name: redis-cluster-operator